// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/roompb/room.proto

package roompb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClientMessage — 클라이언트 → 서버 페이로드 래퍼.
// Phase 1 은 Move 만. 후속 Phase 에서 Join / Leave / Chat 추가 예정.
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Move
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_api_proto_roompb_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roompb_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_roompb_room_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetMove() *Move {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Move struct {
	Move *Move `protobuf:"bytes,1,opt,name=move,proto3,oneof"`
}

func (*ClientMessage_Move) isClientMessage_Payload() {}

// Move — 플레이어의 월드 좌표 보고.
type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X             float64                `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_api_proto_roompb_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_roompb_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_api_proto_roompb_room_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *Move) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Move) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_api_proto_roompb_room_proto protoreflect.FileDescriptor

const file_api_proto_roompb_room_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/roompb/room.proto\x12\aroom.v1\"?\n" +
	"\rClientMessage\x12#\n" +
	"\x04move\x18\x01 \x01(\v2\r.room.v1.MoveH\x00R\x04moveB\t\n" +
	"\apayload\"?\n" +
	"\x04Move\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x01R\x01yB8Z6github.com/kimsehoon/stagesync/api/proto/roompb;roompbb\x06proto3"

var (
	file_api_proto_roompb_room_proto_rawDescOnce sync.Once
	file_api_proto_roompb_room_proto_rawDescData []byte
)

func file_api_proto_roompb_room_proto_rawDescGZIP() []byte {
	file_api_proto_roompb_room_proto_rawDescOnce.Do(func() {
		file_api_proto_roompb_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_roompb_room_proto_rawDesc), len(file_api_proto_roompb_room_proto_rawDesc)))
	})
	return file_api_proto_roompb_room_proto_rawDescData
}

var file_api_proto_roompb_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_roompb_room_proto_goTypes = []any{
	(*ClientMessage)(nil), // 0: room.v1.ClientMessage
	(*Move)(nil),          // 1: room.v1.Move
}
var file_api_proto_roompb_room_proto_depIdxs = []int32{
	1, // 0: room.v1.ClientMessage.move:type_name -> room.v1.Move
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_roompb_room_proto_init() }
func file_api_proto_roompb_room_proto_init() {
	if File_api_proto_roompb_room_proto != nil {
		return
	}
	file_api_proto_roompb_room_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientMessage_Move)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_roompb_room_proto_rawDesc), len(file_api_proto_roompb_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_roompb_room_proto_goTypes,
		DependencyIndexes: file_api_proto_roompb_room_proto_depIdxs,
		MessageInfos:      file_api_proto_roompb_room_proto_msgTypes,
	}.Build()
	File_api_proto_roompb_room_proto = out.File
	file_api_proto_roompb_room_proto_goTypes = nil
	file_api_proto_roompb_room_proto_depIdxs = nil
}
